services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    image: ghcr.io/catgrep/downtime.is:${TAG:-latest}
    ports:
      - "8080:8080"

  caddy:
    image: caddy:2.9.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  caddy_data:
  caddy_config:
